'use client';

import React from 'react';
import Image from 'next/image';

interface ReportTemplateProps {
  title: string;
  patientName: string;
  date: string;
  reportContent: string;
  doctor?: string;
}

const ReportTemplate: React.FC<ReportTemplateProps> = ({ 
  title, 
  patientName, 
  date, 
  reportContent, 
  doctor = "HealthGuardian AI"
}) => {
  // Parse the report content to separate sections
  const sections = reportContent.split('\n\n').filter(section => section.trim() !== '');
  
  return (
    <div id="report-template" className="w-[800px] min-h-[1120px] p-10 bg-white text-gray-800 font-sans">
      {/* Header */}
      <div className="flex justify-between items-center pb-6 border-b border-primary">
        <div className="flex items-center gap-4">
          <div className="w-16 h-16 relative">
            <Image src="/images/medical-cross.svg" fill alt="HealthGuardian Logo" className="object-contain" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-primary">HealthGuardian AI</h1>
            <p className="text-sm text-gray-500">Advanced Healthcare Assistance</p>
          </div>
        </div>
        <div className="text-right">
          <h2 className="text-xl font-bold text-primary">Medical Report</h2>
          <p className="text-sm text-gray-500">{date}</p>
        </div>
      </div>
      
      {/* Patient Information */}
      <div className="mt-8 p-6 bg-[#F5FAFD] rounded-lg border border-gray-200">
        <h2 className="text-lg font-bold text-primary mb-4">Patient Information</h2>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <p className="text-sm text-gray-500">Patient Name:</p>
            <p className="font-medium">{patientName}</p>
          </div>
          <div>
            <p className="text-sm text-gray-500">Date:</p>
            <p className="font-medium">{date}</p>
          </div>
          <div>
            <p className="text-sm text-gray-500">Report ID:</p>
            <p className="font-medium">{`HG-${Date.now().toString().slice(-8)}`}</p>
          </div>
          <div>
            <p className="text-sm text-gray-500">Provider:</p>
            <p className="font-medium">{doctor}</p>
          </div>
        </div>
      </div>
      
      {/* Report Title */}
      <div className="mt-8 mb-6">
        <h1 className="text-2xl font-bold text-center text-primary pb-2 border-b-2 border-primary">{title}</h1>
      </div>
      
      {/* Report Content */}
      <div className="mt-6 space-y-6">
        {sections.map((section, index) => {
          // Check if section is a header (all caps or ends with a colon)
          const isHeader = section.toUpperCase() === section || section.trim().endsWith(':');
          
          if (isHeader) {
            return (
              <h3 key={index} className="text-lg font-bold text-primary mt-6">{section}</h3>
            );
          }
          
          return (
            <div key={index} className="text-gray-700 leading-relaxed">
              {section.split('\n').map((paragraph, pIndex) => (
                <p key={`p-${index}-${pIndex}`} className="mb-3">{paragraph}</p>
              ))}
            </div>
          );
        })}
      </div>
      
      {/* Footer */}
      <div className="mt-12 pt-6 border-t border-gray-200">
        <div className="flex justify-between items-center">
          <div>
            <p className="text-sm text-gray-500">Generated by HealthGuardian AI</p>
            <p className="text-xs text-gray-400">This report is for informational purposes only and is not a substitute for professional medical advice.</p>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 relative">
              <Image src="/images/brain-tech.svg" fill alt="AI Technology" className="object-contain" />
            </div>
            <p className="text-sm font-medium text-primary">AI-Powered Healthcare</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportTemplate; 